### ISSUE TITLE
提个建议，新增库函数版本的暂停录制

### ISSUE THREAD

**Issue by LuoShiLiang** [whoissunshijia/ue4-ffmpeg#4]
用库函数的方式

**Comment by zhangdduo** [comment]
我写了一个actor类，用来控制录制和暂停

**Comment by zhangdduo** [comment]
开始录制
bool  AFFRecordActor::StartRecord()
{
	PressStopNum += 1;
	//防止正在录制的时候又按了录制键
	if (PressStopNum<=1)
	{
		CreateRecordWindow();
		UFFmpegDirector_d = NewObject<UFFmpegDirector>();
		UFFmpegDirector_d->AddToRoot();
		UWorld* world = GEditor->GetPIEWorldContext()->World();
		UFFmpegDirector_d->Initialize_Director(world, OutFileName, UseGPU, VideoFilter, FPS, VideoBitRate, AudioDelay, SoundVolume);
		
		return true;
	}
	return false;
}
//停止录制
void AFFRecordActor::StopRecord()
{
	PressStopNum = 0;
	if (UFFmpegDirector_d)
	{
		UFFmpegDirector_d->EndWindowReader(true);
		if (RecordWindow)
		{
			RecordWindow->DestroyWindowImmediately();
		}
		RecordWindow = nullptr;
	}
	isStopRecord = true;
}

**Comment by LuoShiLiang** [comment]
感觉可以改写库函数在当前世界生成一个自己的Actor，然后存放record对象引用在这个Actor当中，这样使用会方便点，全局直接调用

**Comment by LuoShiLiang** [comment]
你这部分代码能补全点吗？

**Comment by zhangdduo** [comment]
> 你这部分代码能补全点吗？
我在录制的时候创建了一个slate窗口，然后停止的时候删除了。
大概是这样，我改的比较多
.h文件
// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "FFRecordActor.generated.h"
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FMyUpLoadFileFinshDelegate, FString, str);
class UFFmpegDirector;
UCLASS()
class UFFMPEG_API AFFRecordActor : public AActor
{
	GENERATED_BODY()
public:
	//FString VideoFilter, bool UseGPU, int FPS, int VideoBitRate, float AudioDelay, float SoundVolume
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		FString VideoName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		FString VideoFilter;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		bool UseGPU;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int FPS;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int VideoBitRate;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		float AudioDelay;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		float SoundVolume;
	//视频质量控制
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int qmin;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int qmax;
	//是否上传视频到服务器
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		bool bUploadServer;
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = HttpOnRequestProgress)
		bool OnUpload;
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = HttpOnRequestProgress)
		int32 Percentage;//上传%比
	
public:	
	// Sets default values for this actor's properties
	AFFRecordActor();
	UFUNCTION(BlueprintCallable)
		bool StartRecord();
	UFUNCTION(BlueprintCallable)
		void StopRecord();
	//
	void UploadFileFinsh(FString url);
	UPROPERTY(BlueprintAssignable)	//  蓝图可以动态地为委托赋予事件
		FMyUpLoadFileFinshDelegate UpLoadFileFinshDelelegate;// 多播委托实例，在Broadcast之后调用该委托上的方法
protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;
	void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
private:
	//
	FText GetRecordTime()const;
	//记录
	int PressStopNum;
	//创建slate窗口
	void CreateRecordWindow();
	//录制窗口
	TSharedPtr<SWindow> RecordWindow;
	UFFmpegDirector* UFFmpegDirector_d;
	//录制文件路径
	FString			filepath;
	FString			FileName;
	//是否是停止录制了
	bool			b_IsStopRecord;
	int				n_frame;
};
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
.ccp
// Fill out your copyright notice in the Description page of Project Settings.


#include "FFRecordActor.h"
#include "FFmpegDirector.h"
#include "Windows/MinWindows.h"
#include "PlatformProcess.h"
#include "Time.h"
#include <string>
#include "FileManagerGeneric.h"

// Sets default values
AFFRecordActor::AFFRecordActor()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	UFFmpegDirector_d = nullptr;
	VideoName = "Record";
	FPS = 24;
	VideoBitRate = 20000;
	SoundVolume = 1.0;
	qmin = 10;
	qmax = 18;

}

bool  AFFRecordActor::StartRecord()
{
	//防止正在录制的时候又按了录制键
	PressStopNum += 1;
	if (PressStopNum<=1)
	{
		//获取系统时间
		SYSTEMTIME sys;
		GetLocalTime(&sys);
		filepath = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir() + "RevoLiveRecord/");
		FileName = FString::Printf(TEXT("%s_%d_%d_%d_%d_%d_%d.mp4"), *VideoName, sys.wYear, sys.wMonth, sys.wDay, sys.wHour, sys.wMinute, sys.wSecond);
		FString FilePathName = filepath + FileName;
		FPlatformFileManager::Get().GetPlatformFile().CreateDirectoryTree(*FPaths::GetPath(FilePathName));
		//创建录制窗口
		CreateRecordWindow();
		UFFmpegDirector_d = NewObject<UFFmpegDirector>();
		UFFmpegDirector_d->AddToRoot();
		UWorld* world = GEditor->GetPIEWorldContext()->World();
		UFFmpegDirector_d->Initialize_Director(world, FilePathName, UseGPU, VideoFilter, FPS, VideoBitRate, AudioDelay, SoundVolume,qmin,qmax);
		
		return true;
	}
	return false;
}

void AFFRecordActor::StopRecord()
{
	PressStopNum = 0;
	if (UFFmpegDirector_d)
	{
		UFFmpegDirector_d->EndWindowReader(true);
		if (RecordWindow)
		{
			RecordWindow->DestroyWindowImmediately();
		}
		RecordWindow = nullptr;
	}
}

void AFFRecordActor::UploadFileFinsh(FString url)
{
	UpLoadFileFinshDelelegate.Broadcast(url);
}

FText AFFRecordActor::GetRecordTime() const 
{
	return FText::FromString("hahha.....");
}
void AFFRecordActor::CreateRecordWindow()
{
	
}
// Called when the game starts or when spawned
void AFFRecordActor::BeginPlay()
{
	Super::BeginPlay();
	b_IsStopRecord = false;
	PressStopNum = 0;
	AudioDelay = 0;

}

// Called every frame
void AFFRecordActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	AudioDelay -= DeltaTime;	
	
}

void AFFRecordActor::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);
	if (RecordWindow)
	{
		RecordWindow->DestroyWindowImmediately();
	}
	RecordWindow = nullptr;
	AudioDelay = 0;
}

**Comment by zhangdduo** [comment]
> 你这部分代码能补全点吗？
我在录制的时候创建了一个slate窗口，然后停止的时候删除了。
大概是这样，我改的比较多
.h文件
// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "FFRecordActor.generated.h"
DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FMyUpLoadFileFinshDelegate, FString, str);
class UFFmpegDirector;
UCLASS()
class UFFMPEG_API AFFRecordActor : public AActor
{
	GENERATED_BODY()
public:
	//FString VideoFilter, bool UseGPU, int FPS, int VideoBitRate, float AudioDelay, float SoundVolume
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		FString VideoName;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		FString VideoFilter;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		bool UseGPU;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int FPS;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int VideoBitRate;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		float AudioDelay;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		float SoundVolume;
	//视频质量控制
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int qmin;
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		int qmax;
	//是否上传视频到服务器
	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "FFRecord")
		bool bUploadServer;
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = HttpOnRequestProgress)
		bool OnUpload;
	UPROPERTY(BlueprintReadWrite, EditAnywhere, Category = HttpOnRequestProgress)
		int32 Percentage;//上传%比
	
public:	
	// Sets default values for this actor's properties
	AFFRecordActor();
	UFUNCTION(BlueprintCallable)
		bool StartRecord();
	UFUNCTION(BlueprintCallable)
		void StopRecord();
	//
	void UploadFileFinsh(FString url);
	UPROPERTY(BlueprintAssignable)	//  蓝图可以动态地为委托赋予事件
		FMyUpLoadFileFinshDelegate UpLoadFileFinshDelelegate;// 多播委托实例，在Broadcast之后调用该委托上的方法
protected:
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:	
	// Called every frame
	virtual void Tick(float DeltaTime) override;
	void EndPlay(const EEndPlayReason::Type EndPlayReason) override;
private:
	//
	FText GetRecordTime()const;
	//记录
	int PressStopNum;
	//创建slate窗口
	void CreateRecordWindow();
	//录制窗口
	TSharedPtr<SWindow> RecordWindow;
	UFFmpegDirector* UFFmpegDirector_d;
	//录制文件路径
	FString			filepath;
	FString			FileName;
	//是否是停止录制了
	bool			b_IsStopRecord;
	int				n_frame;
};
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。
.ccp
// Fill out your copyright notice in the Description page of Project Settings.


#include "FFRecordActor.h"
#include "FFmpegDirector.h"
#include "Windows/MinWindows.h"
#include "PlatformProcess.h"
#include "Time.h"
#include <string>
#include "FileManagerGeneric.h"

// Sets default values
AFFRecordActor::AFFRecordActor()
{
 	// Set this actor to call Tick() every frame.  You can turn this off to improve performance if you don't need it.
	PrimaryActorTick.bCanEverTick = true;
	UFFmpegDirector_d = nullptr;
	VideoName = "Record";
	FPS = 24;
	VideoBitRate = 20000;
	SoundVolume = 1.0;
	qmin = 10;
	qmax = 18;

}

bool  AFFRecordActor::StartRecord()
{
	//防止正在录制的时候又按了录制键
	PressStopNum += 1;
	if (PressStopNum<=1)
	{
		//获取系统时间
		SYSTEMTIME sys;
		GetLocalTime(&sys);
		filepath = FPaths::ConvertRelativePathToFull(FPaths::ProjectSavedDir() + "RevoLiveRecord/");
		FileName = FString::Printf(TEXT("%s_%d_%d_%d_%d_%d_%d.mp4"), *VideoName, sys.wYear, sys.wMonth, sys.wDay, sys.wHour, sys.wMinute, sys.wSecond);
		FString FilePathName = filepath + FileName;
		FPlatformFileManager::Get().GetPlatformFile().CreateDirectoryTree(*FPaths::GetPath(FilePathName));
		//创建录制窗口
		CreateRecordWindow();
		UFFmpegDirector_d = NewObject<UFFmpegDirector>();
		UFFmpegDirector_d->AddToRoot();
		UWorld* world = GEditor->GetPIEWorldContext()->World();
		UFFmpegDirector_d->Initialize_Director(world, FilePathName, UseGPU, VideoFilter, FPS, VideoBitRate, AudioDelay, SoundVolume,qmin,qmax);
		
		return true;
	}
	return false;
}

void AFFRecordActor::StopRecord()
{
	PressStopNum = 0;
	if (UFFmpegDirector_d)
	{
		UFFmpegDirector_d->EndWindowReader(true);
		if (RecordWindow)
		{
			RecordWindow->DestroyWindowImmediately();
		}
		RecordWindow = nullptr;
	}
}

void AFFRecordActor::UploadFileFinsh(FString url)
{
	UpLoadFileFinshDelelegate.Broadcast(url);
}

FText AFFRecordActor::GetRecordTime() const 
{
	return FText::FromString("hahha.....");
}
void AFFRecordActor::CreateRecordWindow()
{
	
}
// Called when the game starts or when spawned
void AFFRecordActor::BeginPlay()
{
	Super::BeginPlay();
	b_IsStopRecord = false;
	PressStopNum = 0;
	AudioDelay = 0;

}

// Called every frame
void AFFRecordActor::Tick(float DeltaTime)
{
	Super::Tick(DeltaTime);
	AudioDelay -= DeltaTime;	
	
}

void AFFRecordActor::EndPlay(const EEndPlayReason::Type EndPlayReason)
{
	Super::EndPlay(EndPlayReason);
	if (RecordWindow)
	{
		RecordWindow->DestroyWindowImmediately();
	}
	RecordWindow = nullptr;
	AudioDelay = 0;
}
